dist: trusty
os:
- linux
- osx
language: c
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add - ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq pkg-config zip g++ zlib1g-dev unzip python openjdk-8-jdk bazel ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bazel ; fi
script:
- bazel test --conlyopt=-std=c99 -c opt //ryu/... //src/...
- bazel run --conlyopt=-std=c99 -c opt //ryu/benchmark
- bazel test --conlyopt=-std=c99 -c opt --copt=-DONLY_64_BIT_OPS_RYU //ryu/...
- bazel run --conlyopt=-std=c99 -c opt --copt=-DONLY_64_BIT_OPS_RYU //ryu/benchmark
